services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: Deiibrn19
    ports:
      - '5433:5432'
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    image: redis:8
    command: ['redis-server', '--appendonly', 'yes', '--maxmemory-policy', 'noeviction']
    ports:
      - '6380:6379'
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
